# Generated by Django 5.0.14 on 2026-05-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0027_alter_csmfeedback_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmfeedback',
            name='client_type_other',
            field=models.CharField(blank=True, help_text='Required when client type is Others', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='client_type',
            field=models.CharField(choices=[('Student', 'Student'), ('DOST Employee', 'DOST Employee'), ('Other Government Employee', 'Other Government Employee'), ('Librarian/Library Staff', 'Librarian/Library Staff'), ('Teaching Personnel', 'Teaching Personnel'), ('Administrative Personnel', 'Administrative Personnel'), ('Researcher', 'Researcher'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='csmfeedback',
            name='company',
            field=models.CharField(blank=True, help_text='Optional organization or affiliation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securityauditlogentry',
            name='event_type',
            field=models.CharField(choices=[('activity', 'Activity'), ('error', 'Error'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('role_change', 'Role change'), ('access_change', 'Access change'), ('security_update', 'Security update'), ('manual_note', 'Manual note')], default='manual_note', max_length=30),
        ),
    ]
